apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend #common name of the deployment
  labels:
    app: sa-frontend #label, used by loadbalancer
spec:
  selector:
    matchLabels:
      app: sa-frontend #selects the pods with matching label
  replicas: 2                                             #number of pods within the deployment
  minReadySeconds: 15
  strategy:
    type: RollingUpdate #deployment strategy, what is the best strategy, explore
    rollingUpdate: 
      maxUnavailable: 1 #number of maximum unavailable pods while rolling the update
      maxSurge: 1 #max number of pods added to the deployment, in this case max of 3 pods
  template:
    metadata:
      labels:
        app: sa-frontend #template for creating the pods, label matches the selector in the deployment
    spec:
      containers:
        - image: andrejpopovski123/sentiment-analysis-frontend
          imagePullPolicy: Always #it will pull the container images on each redeployment
          name: sa-frontend
          ports:
            - containerPort: 80
