apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  selector:
     matchLabels:
       app: sa-logic
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis-logic #my image took too long to push to dockerhub, using the one from the blog.
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
