apiVersion: v1
kind: Service
metadata:
  name: sa-logic #name of the service
spec:
  ports:
    - port: 80 #port that the service is accesible
      protocol: TCP
      targetPort: 5000 #port of the pods in the deployment
  selector:
    app: sa-logic #labels of the pods